spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to the loans API"
  contactDetails:
    name: "Liliherax - Product Owner"
    email: "__"
  onCallSupport:
    - (011)-GOOD-PLEASE-HELP-RUNNING-THIS