build:
  version: "3.0"

cards:
  message: "Welcome to the cards API"
  contactDetails:
    name: "Liliherax - Product Owner"
    email: "__"
  onCallSupport:
    - (011)-GOOD-PLEASE-HELP-RUNNING-THIS